### ISSUE TITLE
sorry for bothering

### ISSUE THREAD

**Issue by qiuxuelaici** [kit57/heartbeat_classification#1]
Hello, I would like to ask where the data used in your experiment came from. If it is not convenient to inform, please forgive me for interrupting. Thank you!

**Comment by kit57** [comment]
@qiuxuelaici Not bothering at all. Here you can find it: https://www.kaggle.com/kinguistics/heartbeat-sounds
Have fun!

**Comment by qiuxuelaici** [comment]
Thank you very much for your reply.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Laura Valencia Gracia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 晚上7:07
收件人:&nbsp;"kit57/heartbeat_classification"<heartbeat_classification@noreply.github.com&gt;;
抄送:&nbsp;"一路向北"<123182566@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kit57/heartbeat_classification] sorry for bothering (#1)





 
Not bothering at all. Here you can find it: https://www.kaggle.com/kinguistics/heartbeat-sounds
 Have fun!
